Vagrant.configure("2") do |config|
  config.vm.define :saltmaster do |saltmaster|
    saltmaster.vm.box = "centos/7"
    saltmaster.vm.network "private_network", ip: "192.168.122.2"
    saltmaster.vm.hostname = "saltmaster"
    saltmaster.vm.provider :libvirt do |domain|
      domain.memory = 1024
      domain.cpus = 1
      domain.nested = true
      domain.volume_cache = 'none'
    end
  end
end