Vagrant.configure("2") do |config|
  config.vm.define :saltminion do |saltminion|
    saltminion.vm.box = "centos/7"
    saltminion.vm.network "private_network", ip: "192.168.122.3"
    saltminion.vm.hostname = "saltminion"
    saltminion.vm.provider :libvirt do |domain|
      domain.memory = 1024
      domain.cpus = 1
      domain.nested = true
      domain.volume_cache = 'none'
    end
  end
end